version: '2'
services:
  app:
    image: 'docker.io/microservice/microservices-architecture-overview-resource-service:latest'
    build:
      context: .
    container_name: resource-service
    depends_on:
      - postgresqldb
    ports:
      - 8081:8081
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/resourceservice
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop

  postgresqldb:
    image: 'postgres:13.1-alpine'
    container_name: postgresqldb
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=resourceservice
  song-service:
    image: 'docker.io/microservice/microservices-architecture-overview-song-service:latest'
    build:
      context: .
    container_name: song-service
    depends_on:
      - postgresqldb_songservice
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb_songservice:5432/songservice
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop

  postgresqldb_songservice:
    image: 'postgres:13.1-alpine'
    container_name: postgresqldb_songservice
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=songservice