apiVersion: v1
kind: Service
metadata:
  name: microservices-architecture-overview-service
  labels:
    app: microservices-architecture-overview
spec:
  type: ClusterIP
  selector:
    app: microservices-architecture-overview
  ports:
    - port: 8082
      targetPort: 8082