server:
  port: 8080
# datasource configuration
spring:
  application:
    name: song-service

song-service:
  path: /api/v1/songs
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka